### PR TITLE
Caffe classification: continuous mode

### PR DESCRIPTION
**Pull request by dsavenko**
Hi,

This PR adds continuous mode to `caffe-classification`. In this mode (and calling option), `caffe-classification` classsifies not a single image, but a set of images (found by tag `imagenet`) continuously into the output file.

The default mode works the same as before.

### CODE REVIEW

**Comment by gfursin** [comment]
I saw you added boost libs (timer) - I don't know how it will influence scenarios on Android, i.e. right now we do not add boost libs there (they are linked to caffe.so). Since classification is separate app, boost libs are not linked there and it may seem that we may need to add them to scenarios on Android which I would prefer to avoid ... Is it possible to use xopenme_clock_start/end to avoid dependency on boost ... I can add a new function to this interface to get timers ...

**Comment by dsavenko** [comment]
Hm... I don't use Boost timers. I added Boost filesystem to traverse files in directories. I can rewrite the traversal logic without Boost, if you anticipate problems here.

**Comment by gfursin** [comment]
Actually just added function xopenme_get_timer(int timer) to xopenme, so if you rebuild this package, you will get the new function available - you can just use it ...

**Comment by gfursin** [comment]
Oh, that's right - dnn_timer is your own function - but again, you can just use xopenme ...
As for traversing files, there is another possibility to avoid using boost - maybe you can give a text file with list of images to this program (which will be prepared by CK higher-level module) - in such case again you will not need to do complex stuff in this C program and you will not need boost ... What do you think?

**Comment by dsavenko** [comment]
I'd actually prefer to leave it as is and deal with any potential problems if we face them. I don't see directory traversal as complex stuff, and you need boost for caffe anyway. Preparing a text file and reading it afterwards will be more complex.

**Comment by gfursin** [comment]
What I mean is that boost is linked inside caffe, but it seems that this classification will now need an external boost - I plan to substitute CPU and OpenCL Android scenarios with this version soon, so if suddenly external boost will be required, most of the mobiles will not be able to run our Android app scenarios ... I also prefer to have minimal dependencies in such apps particularly on huge libs like Boost ...

**Comment by gfursin** [comment]
Another thing is that we want to unify use of timers via xOpenME to avoid having too many different ways of collecting timers and to make them portable across different OS - this is one of the main purposes of xOpenME, so it's better to improve it rather than adding yet another implementation of timers ;) ...

**Comment by gfursin** [comment]
BTW, sorry for mixing up - Boost is about files not timers, but I still think that 
a) we should not have extra timer routines since we already have one in xOpenME
b) navigating through filesystem via Boost sounds scary to me and may break compatibility - I can check it later if it will work on Samsung S7 without boost library (i.e. if these functions will be linked to the binary) - maybe it will work out ...

**Comment by gfursin** [comment]
By the way, I just checked your patch and caffe-classification seems to be working on S7 (seems to be linking boost). But on Windows 10 64-bit I got an error: 
> classification.cpp(311) : error C4716: 'classify_continuously': must return a value

**Comment by gfursin** [comment]
Which means that we can probably use Boost for now ...

**Comment by dsavenko** [comment]
About timers, I've just used the function from DNN proxies without much thinking about it :) I agree we should use xOpenME - will change it.

About the return value error - yeah, my bad, I'll fix it. Apparently, the Microsoft compiler is less permissive than GCC.

**Comment by gfursin** [comment]
Sure, I see ;) ! Thanks a lot!

**Comment by dsavenko** [comment]
Timers and the compilation error should be fixed. Please, take a look.

**Pull request merged**
