### PR TITLE
Problem with "caffe-time" program when using CUDA-based caffe

### PR DESCRIPTION
**Pull request by DVEfremov**
- add all commands support from original caffe with same arguments support without gflag

### CODE REVIEW

**Comment by DVEfremov** [comment]
Please do not submit 
I'll merge Anton's commit 
https://github.com/dividiti/ck-caffe/commit/6d6208344ee9c299797f8c031e77686f53775930

**Comment by DVEfremov** [comment]
So I've done merge of required changes.
@psyhtest, please review

**Comment by psyhtest** [comment]
LGTM - thanks!

**Comment by gfursin** [comment]
Hi all! Actually, it was not completely working since we force USE_CPU and caffe-time and caffe-classification didn't use CUDA even though we link with CUDA-based Caffe (but CPU sub-version was used). To make it work, I created:
* caffe-time-cuda
* caffe-classification-cuda
Basically, there I add NVCC as compiler (otherwise GCC doesn't find CUDA libs), removed USE_CPU, and they seems to work fine now. However, @DVEfremov may I ask you to check that the flag --gpu is propogated correctly inside, please?
Also, maybe one day we will be able to merge them into one CK program, but for now it's quite tricky, so I wouldn't bother for now ...

**Pull request merged**
